from typing import Any, Optional

class Response:
    status_code: int
    def json(self) -> Any: ...

def get(url: str, timeout: Optional[float] = ..., **kwargs: Any) -> Response: ...

class exceptions:
    class Timeout(Exception): ...
    class ConnectionError(Exception): ...
