from typing import Any, Callable, Tuple

class Request:
    method: str
    def get_json(self) -> Any: ...
    @property
    def is_json(self) -> bool: ...

request: Request

class Flask:
    def __init__(self, import_name: str, **kwargs: Any) -> None: ...
    def route(self, rule: str, **options: Any) -> Callable[..., Any]: ...
    def run(self, **kwargs: Any) -> None: ...

def jsonify(*args: Any, **kwargs: Any) -> Any: ...
